name: Kaggle to AWS Workflow

on:
  push:
    branches:
      - main

jobs:
  kaggle-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install kaggle boto3 pandas pymysql

      - name: Download Kaggle Dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          kaggle datasets download -d demo12 -p ./data
          unzip ./data/demo12.zip -d ./data

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python -c "
          import boto3
          s3 = boto3.client('s3')
          with open('./data/<dataset-file>', 'rb') as f:
              s3.upload_fileobj(f, '<s3-bucket-name>', '<dataset-file>')
          "

