AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: MyEMRCluster
      ReleaseLabel: emr-7.0.0
      Applications:
        - Name: Spark
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1  
          InstanceType: m5.xlarge
          Name: MASTER
        CoreInstanceGroup: 
          InstanceCount: 2
          InstanceType: m5.xlarge
          Name: CORE
        Ec2SubnetIds: 
          - subnet-01b68b68cd8eb4f82
        Ec2KeyName: EC2_F
      JobFlowRole: "EMR_EC2_DefaultRole"
      ServiceRole: "EMR_DefaultRole"
          
  MySparkStep:
    Type: AWS::EMR::Step
    Properties:
      Name: MySparkStep
      ActionOnFailure: CONTINUE
      HadoopJarStep:
        Jar: command-runner.jar
        Args:
          - spark-submit
          - --deploy-mode
          - cluster
          - --class
          - org.apache.spark.deploy.Mysparkob 
          - --jars
          - s3://requiredfiles2323/mysql-connector-java-8.0.23.jar 
          - s3://group8project/emrpy.py
      JobFlowId: !Ref MyEMRCluster

  DataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - MyEMRCluster
      - MySparkStep
    Properties:
      Name: finalcrawl
      DatabaseName: default
      Targets:
        S3Targets:
          - Path: s3://group8project/credit_card_fraud/output/
      Role: arn:aws:iam::600497572483:role/LabRole
